### ISSUE TITLE
[Idea] MapStruct - Spring에 Bean으로 등록하기

### ISSUE THREAD

**Issue by phdljr** [phdljr/one-click-recipe#13]
## 내용
> 자유롭게 작성해 주세요.
> 예시가 있다면 이해하는데 많은 도움이 됩니다!

매퍼 구현체를 빈으로 등록시켜서 사용한다면 더 좋지 않을까 싶네요.
```
@Mapper(componentModel = ComponentModel.SPRING)
```
이렇게 된다면, 서비스나 컨트롤러쪽에서 매퍼 구현체를 주입받아 사용할 수 있습니다.
`UserMapper.INSTANCE.toDto()` 를 할 필요 없이, `userMapper.toDto()` 형식으로 말이죠

어떤가요?
참조: https://velog.io/@backtony/Spring-Mapper-Mapstruct-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

**Comment by pangseon** [comment]
기존방식과 위 방식의 차이점이 어떤건가요?

**Comment by phdljr** [comment]
> 기존방식과 위 방식의 차이점이 어떤건가요?

기존에는 인터페이스에 생성된 `INSTANCE`를 통해서 사용했다면,
이제 매퍼를 빈으로 주입받아서 사용할 수 있습니다.
